services:
  server:
    build: ./server
    ports:
      - 3000:3000
    networks:
      - mynetwork

  client:
    build: ./client
    ports:
      - 4200:4200
    networks:
      - mynetwork
    depends_on:
      - server

networks:
  mynetwork:
    driver: bridge